### ISSUE TITLE
Unexpected dash in CSS variable names

### ISSUE THREAD

**Issue by christoph-fricke** [terrazzoapp/terrazzo#390]
Given some tokens with a number in the name such as these:

```json
{
  "space": {
    "$type": "dimension",
    "large": { "$value": { "value": 1.5, "unit": "rem" } },
    "x-large": { "$value": { "value": 2, "unit": "rem" } },
    "2x-large": { "$value": { "value": 3, "unit": "rem" } },
    "3x-large": { "$value": { "value": 4, "unit": "rem" } }
  },
}
```

Then the `@terrazzo/plugin-css` creates the following CSS variables:

```css
:root {
  --space-large: 1.5rem;
  --space-x-large: 2rem;
  --space-2-x-large: 3rem;
  --space-3-x-large: 4rem;
}
```

I am surprised by the dash between the numbers and "x", which is added by the `makeCSSVar` function from _@terrazzo/token-tools/css_. Is this CSS naming behavior intended? I would have expected the following names:

```css
:root {
  --space-large: 1.5rem;
  --space-x-large: 2rem;
  --space-2x-large: 3rem;
  --space-3x-large: 4rem;
}
```
